[build]
  command = "cd frontend && npm install && npm run build && cd ../netlify/functions && npm install"
  publish = "frontend/build"
  base = "."

[dev]
  command = "npm start --prefix frontend"
  targetPort = 3000

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
